"use client";
import AdminShell from "@/components/AdminShell";
import CertificateButtons from "@/components/CertificateViewer";
import { useEffect, useState } from "react";
import { Plus, ChartNoAxesColumnIncreasing, X, Copy, Mail, Check, Loader2, Trash2 } from "lucide-react";

const empty = { firstName:"", lastName:"", email:"", jobTitle:"", department:"", phone:"", employmentStatus:"active", startDate:"", currentEquity:"" };
const fields = [["First name","firstName","text"],["Last name","lastName","text"],["Email","email","email"],["Job title","jobTitle","text"],["Department","department","text"],["Phone","phone","tel"],["Start date","startDate","date"],["Initial equity allocation","currentEquity","number"]] as const;

export default function Page() {
  const [staff,setStaff]=useState<any[]>([]), [form,setForm]=useState(empty), [open,setOpen]=useState(false);
  const [created,setCreated]=useState<any>(), [equity,setEquity]=useState<any>(), [msg,setMsg]=useState("");
  const [copied,setCopied]=useState(false), [sending,setSending]=useState(false), [emailSent,setEmailSent]=useState(false), [emailError,setEmailError]=useState("");
  const [savingEquity,setSavingEquity]=useState(false);
  async function load(){const r=await fetch("/api/staff");if(r.ok)setStaff((await r.json()).staff)}
  useEffect(()=>{load()},[]);
  async function create(e:React.FormEvent){e.preventDefault();setMsg("");const r=await fetch("/api/staff",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(form)}),d=await r.json();if(!r.ok)return setMsg(d.message);setCopied(false);setEmailSent(false);setEmailError("");setCreated(d);setForm(empty);setOpen(false);load()}
  async function saveEquity(e:React.FormEvent){e.preventDefault();if(savingEquity)return;setSavingEquity(true);try{const r=await fetch(`/api/staff/${equity.id}/equity`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(equity)}),d=await r.json();if(!r.ok)return setMsg(d.message);setEquity(null);setMsg("Equity updated successfully.");load()}finally{setSavingEquity(false)}}
  function loginDetails(){return `UpTech Staff Portal\nName: ${created.name}\nEmployee ID: ${created.employeeId}\nEmail: ${created.email}\nTemporary password: ${created.temporaryPassword}\nLogin: ${location.origin}/staff/login\n\nYou must create a new password after your first sign-in.`}
  async function copyDetails(){await navigator.clipboard.writeText(loginDetails());setCopied(true);setTimeout(()=>setCopied(false),2000)}
  async function sendDetails(){setSending(true);setEmailError("");try{const r=await fetch("/api/staff/send-welcome",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({...created,loginUrl:`${location.origin}/staff/login`})});const d=await r.json();if(!r.ok)throw new Error(d.message);setEmailSent(true)}catch(e){setEmailError(e instanceof Error?e.message:"The welcome email could not be sent.")}finally{setSending(false)}}
  async function deleteStaff(member:any){if(!confirm(`Delete ${member.firstName} ${member.lastName}? This permanently removes their login, profile and equity history.`))return;setMsg("");const r=await fetch(`/api/staff/${member.id}`,{method:"DELETE"});const d=await r.json();if(!r.ok)return setMsg(d.message||"Staff member could not be deleted.");setMsg("Staff member deleted successfully.");load()}
  function openEquity(member:any){const total=Number(member.currentEquity||0);setEquity({id:member.id,name:`${member.firstName} ${member.lastName}`,base:total,value:total,equityUnit:member.equityUnit||"allocation",employmentStatus:member.employmentStatus||"active",equityStatus:member.equityStatus||"active",equityAdded:0,period:"",effectiveDate:new Date().toISOString().slice(0,10),note:"",updateId:crypto.randomUUID()})}
  function changeEquityAdded(raw:string){const added=Number(raw||0);setEquity({...equity,equityAdded:raw,value:Number(equity.base)+added})}
  function changeTotalEquity(raw:string){const total=Number(raw||0);setEquity({...equity,value:raw,equityAdded:total-Number(equity.base)})}

  return <AdminShell><main className="max-w-[1200px] mx-auto px-4 sm:px-7 py-8">
    <div className="flex flex-wrap justify-between items-end gap-4"><div><p className="text-brand-700 font-extrabold uppercase tracking-wider text-xs">People &amp; ownership</p><h1 className="text-3xl mt-1">Staff Management</h1><p className="text-ink-soft mt-2">Create staff accounts and maintain equity allocations.</p></div><button onClick={()=>setOpen(true)} className="rounded-full bg-brand text-white px-5 py-3 font-bold flex gap-2"><Plus/>Add staff member</button></div>
    {msg&&<p className="mt-5 bg-white border border-line rounded-card-sm p-4">{msg}</p>}
    {created&&<div role="dialog" aria-modal="true" className="fixed inset-0 z-50 bg-navy/70 p-4 grid place-items-center"><div className="bg-white rounded-card p-6 sm:p-8 max-w-lg w-full shadow-card-lg"><button onClick={()=>setCreated(null)} className="float-right p-2" aria-label="Close"><X/></button><h2 className="text-2xl">Staff member created</h2><p className="text-ink-soft mt-3">Copy these details now. The temporary password will not be shown again.</p><dl className="mt-6 bg-mist rounded-card-sm p-5 space-y-3"><Row k="Name" v={created.name}/><Row k="Employee ID" v={created.employeeId}/><Row k="Email" v={created.email}/><Row k="Temporary password" v={created.temporaryPassword}/></dl><p className="mt-4 text-sm">Login at <strong>/staff/login</strong>. A new password is required after first sign-in.</p>{emailError&&<p role="alert" className="mt-4 rounded-xl bg-red-50 border border-red-200 p-3 text-sm text-red-700">{emailError}</p>}<div className="mt-6 grid sm:grid-cols-2 gap-3"><button onClick={copyDetails} className="min-h-12 rounded-full border border-line px-5 font-bold flex items-center justify-center gap-2 hover:bg-mist">{copied?<><Check className="w-4 h-4 text-green-600"/>Copied</>:<><Copy className="w-4 h-4"/>Copy details</>}</button><button onClick={sendDetails} disabled={sending||emailSent} className="min-h-12 rounded-full bg-brand text-white px-5 font-bold flex items-center justify-center gap-2 disabled:opacity-70">{sending?<><Loader2 className="w-4 h-4 animate-spin"/>Sending…</>:emailSent?<><Check className="w-4 h-4"/>Email sent</>:<><Mail className="w-4 h-4"/>Send email</>}</button></div></div></div>}
    {open&&<form onSubmit={create} className="mt-6 grid sm:grid-cols-2 gap-4 bg-white border border-line rounded-card shadow-card p-5 sm:p-7">{fields.map(([label,key,type])=><label key={key} className="font-bold text-sm">{label}<input type={type} required={["firstName","lastName","email","jobTitle"].includes(key)} step={key==="currentEquity"?"0.01":undefined} min={key==="currentEquity"?"0":undefined} value={form[key]} onChange={e=>setForm({...form,[key]:e.target.value})} className="input"/></label>)}<label className="font-bold text-sm">Employment status<select value={form.employmentStatus} onChange={e=>setForm({...form,employmentStatus:e.target.value})} className="input"><option value="active">Active</option><option value="leave">On leave</option></select></label><div className="sm:col-span-2 flex gap-3"><button className="bg-brand text-white rounded-full px-6 py-3 font-bold">Create secure account</button><button type="button" onClick={()=>setOpen(false)} className="border border-line rounded-full px-6 py-3 font-bold">Cancel</button></div></form>}
    <div className="mt-7 grid md:grid-cols-2 xl:grid-cols-3 gap-4">{staff.length===0?<div className="md:col-span-2 bg-white rounded-card p-10 border border-line text-center text-ink-soft">No staff accounts have been created yet.</div>:staff.map(s=><article key={s.id} className="min-w-0 bg-white rounded-card border border-line shadow-card p-5"><div className="flex justify-between gap-3"><div className="min-w-0"><h2 className="text-xl break-words">{s.firstName} {s.lastName}</h2><p className="text-brand-700 font-bold">{s.employeeId}</p></div><span className="capitalize text-xs font-bold bg-green-50 text-green-700 rounded-full h-fit px-3 py-1">{s.employmentStatus}</span></div><p className="text-ink-soft mt-4 break-words">{s.jobTitle}{s.department?` · ${s.department}`:""}</p><div className="mt-5 pt-5 border-t border-line"><div className="grid grid-cols-2 gap-4 min-w-0"><div className="min-w-0"><p className="text-xs text-ink-soft uppercase font-bold">Total equity</p><strong className="block text-lg sm:text-xl break-all">{Number(s.currentEquity||0).toLocaleString()}</strong></div><div className="min-w-0"><p className="text-xs text-ink-soft uppercase font-bold">Equity added</p><strong className={`block text-lg sm:text-xl break-all ${Number(s.equityAdded||0)<0?"text-red-600":"text-green-700"}`}>{Number(s.equityAdded??s.currentEquity??0)>0?"+":""}{Number(s.equityAdded??s.currentEquity??0).toLocaleString()}</strong></div></div><CertificateButtons staffId={s.id}/><div className="flex justify-end gap-2 mt-4"><button onClick={()=>openEquity(s)} className="p-3 bg-brand/10 text-brand rounded-full" aria-label={`Manage equity for ${s.firstName}`}><ChartNoAxesColumnIncreasing/></button><button onClick={()=>deleteStaff(s)} className="p-3 bg-red-50 text-red-600 rounded-full hover:bg-red-100" aria-label={`Delete ${s.firstName} ${s.lastName}`}><Trash2/></button></div></div></article>)}</div>
    {equity&&<div className="fixed inset-0 z-50 bg-navy/70 p-4 grid place-items-center overflow-y-auto"><form onSubmit={saveEquity} className="bg-white rounded-card p-6 max-w-md w-full my-4 max-h-[90vh] overflow-y-auto"><h2 className="text-2xl">Manage Equity</h2><p className="text-ink-soft mt-2">{equity.name}</p><label className="block font-bold mt-4">Recorded equity unit<select value={equity.equityUnit} onChange={e=>setEquity({...equity,equityUnit:e.target.value})} className="input"><option value="allocation">Equity allocation (unspecified units)</option><option value="ordinary_shares">Ordinary shares (verified share count)</option><option value="percentage">Percentage</option></select></label><div className="grid grid-cols-2 gap-3"><label className="block font-bold mt-4">Employment status<select value={equity.employmentStatus} onChange={e=>setEquity({...equity,employmentStatus:e.target.value})} className="input"><option value="active">Active</option><option value="leave">On leave</option><option value="inactive">Inactive</option><option value="terminated">Terminated</option></select></label><label className="block font-bold mt-4">Equity status<select value={equity.equityStatus} onChange={e=>setEquity({...equity,equityStatus:e.target.value})} className="input"><option value="active">Active</option><option value="inactive">Inactive</option><option value="revoked">Revoked</option></select></label></div><label className="block font-bold mt-5">Period<input type="text" required placeholder="e.g. Q1 2026 or January 2026" value={equity.period} onChange={e=>setEquity({...equity,period:e.target.value})} className="input"/></label><label className="block font-bold mt-4">Equity added for period<input type="number" step="0.01" required value={equity.equityAdded} onChange={e=>changeEquityAdded(e.target.value)} className="input"/><span className="block text-xs font-normal text-ink-soft mt-1">Use a negative number to reduce equity.</span></label><label className="block font-bold mt-4">Total equity<input type="number" min="0" step="0.01" required value={equity.value} onChange={e=>changeTotalEquity(e.target.value)} className="input"/></label><label className="block font-bold mt-4">Effective date<input type="date" required value={equity.effectiveDate} onChange={e=>setEquity({...equity,effectiveDate:e.target.value})} className="input"/></label><label className="block font-bold mt-4">Internal note<textarea value={equity.note} onChange={e=>setEquity({...equity,note:e.target.value})} className="input"/></label><div className="flex gap-3 mt-6"><button className="bg-brand text-white rounded-full px-5 py-3 font-bold">Save update</button><button type="button" onClick={()=>setEquity(null)} className="border border-line rounded-full px-5 py-3 font-bold">Cancel</button></div></form></div>}
  </main></AdminShell>
}
function Row({k,v}:{k:string;v:string}){return <div><dt className="text-xs uppercase text-ink-soft font-bold">{k}</dt><dd className="font-extrabold break-all">{v}</dd></div>}
