import { NextRequest,NextResponse } from "next/server";
import { adminAuth,adminFirestore } from "@/lib/firebase-admin";
import { audit,requireRole } from "@/lib/server-auth";
import { serializeDoc,text } from "@/lib/hr";
import { HR_STATUSES } from "@/types/hr";
import crypto from "crypto";
import { sendSmtpEmail } from "@/lib/smtp";

async function hr(){return requireRole(["hr","super_admin"])}
const emailEscape=(value:string)=>value.replace(/[&<>'"]/g,character=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"})[character]||character);
async function notifyRequiredReading(kind:"policy"|"document",id:string,title:string,description:string){
 const profiles=await adminFirestore.collection("staffProfiles").limit(250).get(),baseUrl=String(process.env.NEXT_PUBLIC_BASE_URL||"http://localhost:3000").replace(/\/$/,""),section=kind==="policy"?"Policies":"Member Documents",url=`${baseUrl}/staff/hr?section=${encodeURIComponent(section)}&record=${encodeURIComponent(id)}`,from=process.env.EMAIL_FROM?.trim()||process.env.EMAIL_USER?.trim()||"uptechincorp@gmail.com";
 const recipients=(await Promise.all(profiles.docs.map(async doc=>{const profile=doc.data(),account=(await adminFirestore.collection("users").doc(doc.id).get()).data()||{};return String(profile.employmentStatus||"active").toLowerCase()==="active"&&account.accountStatus!=="disabled"&&profile.email?{email:String(profile.email),name:`${profile.firstName||""} ${profile.lastName||""}`.trim()||"Team member"}:null}))).filter((item):item is {email:string;name:string}=>Boolean(item));
 let sent=0,failed=0;
 for(const recipient of recipients){try{const result=await sendSmtpEmail({to:recipient.email,from,subject:`Required reading: ${title}`,html:`<!doctype html><html><body style="margin:0;background:#eef4ff;font-family:Arial,sans-serif;color:#10254c"><table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="padding:28px 12px;background:#eef4ff"><tr><td align="center"><table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="max-width:600px;background:#ffffff;border-radius:20px;overflow:hidden"><tr><td style="background:#10254c;padding:28px;color:#ffffff"><div style="font-size:13px;letter-spacing:2px;text-transform:uppercase;color:#b9d1ff">UpTech member update</div><h1 style="margin:8px 0 0;font-size:25px;color:#ffffff">Required ${kind} to review</h1></td></tr><tr><td style="padding:30px"><p>Hello ${emailEscape(recipient.name)},</p><p>HR has published <strong>${emailEscape(title)}</strong> and requires every member to read and acknowledge it.</p>${description?`<p style="color:#51617e">${emailEscape(description).replace(/\n/g,"<br>")}</p>`:""}<table role="presentation" cellspacing="0" cellpadding="0" style="margin:28px auto"><tr><td bgcolor="#2563eb" style="border-radius:999px"><a href="${emailEscape(url)}" style="display:inline-block;padding:14px 28px;color:#ffffff!important;text-decoration:none;font-weight:bold"><span style="color:#ffffff!important">Read and acknowledge</span></a></td></tr></table><p style="font-size:13px;color:#51617e">Sign in to the Member Portal to review the complete ${kind} and record your acknowledgement.</p></td></tr></table></td></tr></table></body></html>`});if(result.configured)sent++;else failed++}catch(error){failed++;console.error("Required reading email failed",recipient.email,error)}}
 return {sent,failed};
}
export async function GET(){
 const user=await hr();if(!user)return NextResponse.json({message:"Forbidden"},{status:403});
 const [employees,requests,leave,policies,documents,announcements]=await Promise.all(["staffProfiles","hrRequests","leaveRequests","hrPolicies","hrDocuments","staffAnnouncements"].map(c=>adminFirestore.collection(c).limit(250).get()));
 const map=(s:FirebaseFirestore.QuerySnapshot)=>s.docs.map(serializeDoc),withAcknowledgements=async(doc:FirebaseFirestore.QueryDocumentSnapshot)=>{const acknowledgements=await doc.ref.collection("acknowledgements").orderBy("acknowledgedAt","desc").get(),revision=doc.data().requiredRevision,valid=revision?acknowledgements.docs.filter(item=>!item.data().revision||item.data().revision===revision):acknowledgements.docs;return {...serializeDoc(doc),acknowledgedCount:valid.length,totalEmployees:employees.size,acknowledgements:valid.map(serializeDoc)}},policyItems=await Promise.all(policies.docs.map(withAcknowledgements)),documentItems=await Promise.all(documents.docs.map(withAcknowledgements));
 return NextResponse.json({employees:map(employees),requests:map(requests),leaveRequests:map(leave),policies:policyItems,documents:documentItems,announcements:map(announcements)},{headers:{"Cache-Control":"private, no-store, max-age=0"}});
}
export async function POST(req:NextRequest){
 const user=await hr();if(!user)return NextResponse.json({message:"Forbidden"},{status:403});
 const b=await req.json(),now=new Date(); let ref:FirebaseFirestore.DocumentReference;
 if(b.action==="createEmployee"){
  const firstName=text(b.firstName,100),lastName=text(b.lastName,100),email=text(b.email,320).toLowerCase(),jobTitle=text(b.jobTitle,200);if(!firstName||!lastName||!email||!jobTitle)return NextResponse.json({message:"First name, last name, email, and job title are required."},{status:400});
  const password=`${crypto.randomBytes(9).toString("base64url")}aA7!`;let uid="";
  try{const employeeId=await adminFirestore.runTransaction(async tx=>{const counter=adminFirestore.collection("counters").doc("staff"),snap=await tx.get(counter),next=Number(snap.data()?.value||0)+1;tx.set(counter,{value:next},{merge:true});return `UPT-${String(next).padStart(4,"0")}`});const account=await adminAuth.createUser({email,password,displayName:`${firstName} ${lastName}`});uid=account.uid;const list=(value:unknown)=>Array.isArray(value)?value.map(x=>text(x,200)).filter(Boolean):text(value).split(",").map(x=>x.trim()).filter(Boolean);const profile={firstName,lastName,email,jobTitle,department:text(b.department,200),phone:text(b.phone,100),supervisor:text(b.supervisor,200),startDate:b.startDate||"",employmentStatus:b.employmentStatus||"Active",emergencyContact:text(b.emergencyContact,500),skills:list(b.skills),certifications:list(b.certifications),trainingCompleted:list(b.trainingCompleted),employeeId,currentEquity:0,createdAt:now,updatedAt:now};await Promise.all([adminFirestore.collection("users").doc(uid).set({email,role:"staff",mustChangePassword:true,accountStatus:"active",createdAt:now}),adminFirestore.collection("staffProfiles").doc(uid).set(profile)]);await audit(user.uid,"employee.created","staff",uid,{employeeId});return NextResponse.json({id:uid,employeeId,email,name:`${firstName} ${lastName}`,temporaryPassword:password},{status:201})}catch(error:any){if(uid)await adminAuth.deleteUser(uid).catch(()=>{});return NextResponse.json({message:error?.code==="auth/email-already-exists"?"A member with this email already exists.":"The member account could not be created."},{status:400})}
 }else if(b.action==="savePolicy"){
  if(!text(b.title,200))return NextResponse.json({message:"Policy title is required."},{status:400});
  ref=b.id?adminFirestore.collection("hrPolicies").doc(b.id):adminFirestore.collection("hrPolicies").doc(text(b.mutationId,100)||crypto.randomUUID()); const old=(await ref.get()).data()||null;
  const version=old&&old.fileUrl!==b.fileUrl?Number(old.version||1)+1:Number(old?.version||1);
  const title=text(b.title,200),description=text(b.description),requiredRevision=crypto.createHash("sha256").update(JSON.stringify([title,description,b.effectiveDate||"",text(b.fileUrl,2000),version])).digest("hex"),shouldNotify=Boolean(b.active)&&Boolean(b.acknowledgementRequired)&&(old?.requiredRevision!==requiredRevision||old?.active!==true||old?.acknowledgementRequired!==true);
  await ref.set({title,description,effectiveDate:b.effectiveDate||"",fileUrl:text(b.fileUrl,2000),fileName:text(b.fileName,300),active:Boolean(b.active),acknowledgementRequired:Boolean(b.acknowledgementRequired),requiredRevision,version,createdAt:old?.createdAt||now,updatedAt:now,updatedBy:user.uid},{merge:true});
  if(shouldNotify){const result=await notifyRequiredReading("policy",ref.id,title,description);await audit(user.uid,"policy.required_reading_notified","hrPolicy",ref.id,result);return NextResponse.json({id:ref.id,message:`Saved. ${result.sent} member${result.sent===1?"":"s"} notified by email.${result.failed?` ${result.failed} email${result.failed===1?"":"s"} could not be sent.`:""}`})}
 }else if(b.action==="saveDocument"){
  if(!text(b.title,200)||!text(b.fileUrl,2000))return NextResponse.json({message:"Document title and file are required."},{status:400});
  ref=b.id?adminFirestore.collection("hrDocuments").doc(b.id):adminFirestore.collection("hrDocuments").doc(text(b.mutationId,100)||crypto.randomUUID());const old=(await ref.get()).data()||null,title=text(b.title,200),description=text(b.description),requiredRevision=crypto.createHash("sha256").update(JSON.stringify([title,description,text(b.fileUrl,2000),text(b.fileName,300)])).digest("hex"),shouldNotify=Boolean(b.active)&&Boolean(b.acknowledgementRequired)&&(old?.requiredRevision!==requiredRevision||old?.active!==true||old?.acknowledgementRequired!==true);await ref.set({title,description,fileUrl:text(b.fileUrl,2000),fileName:text(b.fileName,300),audience:"all_staff",active:Boolean(b.active),acknowledgementRequired:Boolean(b.acknowledgementRequired),requiredRevision,createdAt:b.createdAt?new Date(b.createdAt):old?.createdAt||now,updatedAt:now,updatedBy:user.uid},{merge:true});
  if(shouldNotify){const result=await notifyRequiredReading("document",ref.id,title,description);await audit(user.uid,"document.required_reading_notified","hrDocument",ref.id,result);return NextResponse.json({id:ref.id,message:`Saved. ${result.sent} member${result.sent===1?"":"s"} notified by email.${result.failed?` ${result.failed} email${result.failed===1?"":"s"} could not be sent.`:""}`})}
 }else if(b.action==="saveAnnouncement"){
  if(!text(b.title,200)||!text(b.description))return NextResponse.json({message:"Announcement title and details are required."},{status:400});
  ref=b.id?adminFirestore.collection("staffAnnouncements").doc(b.id):adminFirestore.collection("staffAnnouncements").doc(text(b.mutationId,100)||crypto.randomUUID());await ref.set({title:text(b.title,200),description:text(b.description),publishDate:b.publishDate||now.toISOString().slice(0,10),published:Boolean(b.published),pinned:Boolean(b.pinned),createdAt:b.createdAt?new Date(b.createdAt):now,updatedAt:now,updatedBy:user.uid},{merge:true});
 }else return NextResponse.json({message:"Unsupported action."},{status:400});
 await audit(user.uid,b.action,"hr",ref.id);return NextResponse.json({id:ref.id});
}
export async function PATCH(req:NextRequest){
 const user=await hr();if(!user)return NextResponse.json({message:"Forbidden"},{status:403}); const b=await req.json(),now=new Date();
 if(b.entity==="employee"){
  const allowed=["firstName","lastName","email","phone","jobTitle","department","supervisor","startDate","employmentStatus","emergencyContact","skills","certifications","trainingCompleted"];
  const update=Object.fromEntries(allowed.filter(k=>k in b.data).map(k=>[k,Array.isArray(b.data[k])?b.data[k].map((x:unknown)=>text(x,200)):text(b.data[k],500)]));
  const firstName=String(update.firstName||""),lastName=String(update.lastName||""),email=String(update.email||"").toLowerCase();if(!firstName||!lastName||!email)return NextResponse.json({message:"Name and email cannot be empty."},{status:400});
  try{await adminAuth.updateUser(b.id,{email,displayName:`${firstName} ${lastName}`});await Promise.all([adminFirestore.collection("staffProfiles").doc(b.id).update({...update,email,updatedAt:now,updatedBy:user.uid}),adminFirestore.collection("users").doc(b.id).set({email,updatedAt:now},{merge:true})])}catch(error:any){return NextResponse.json({message:error?.code==="auth/email-already-exists"?"That email is already assigned to another account.":"The member identity could not be updated."},{status:400})}
 }else if(b.entity==="request"||b.entity==="leave"){
  if(!HR_STATUSES.includes(b.status))return NextResponse.json({message:"Invalid status."},{status:400}); const collection=b.entity==="request"?"hrRequests":"leaveRequests",ref=adminFirestore.collection(collection).doc(b.id),snap=await ref.get();if(!snap.exists)return NextResponse.json({message:"Record not found."},{status:404});
  const notes=b.entity==="request"?{internalNotes:text(b.internalNotes),employeeResponse:text(b.employeeResponse)}:{hrNotes:text(b.hrNotes)};
  await ref.update({status:b.status,...notes,updatedAt:now,updatedBy:user.uid}); const employeeId=snap.data()?.employeeId;if(employeeId)await adminFirestore.collection("staffNotifications").add({employeeId,title:`${b.entity==="leave"?"Leave":"HR request"} updated`,message:`Your ${b.entity==="leave"?"leave request":"HR request"} is now ${b.status}.`,entity:b.entity,sourceId:b.id,read:false,createdAt:now});
 }else return NextResponse.json({message:"Unsupported entity."},{status:400});
 await audit(user.uid,`${b.entity}.updated`,b.entity,b.id);return NextResponse.json({success:true});
}
export async function DELETE(req:NextRequest){
 const user=await hr();if(!user)return NextResponse.json({message:"Forbidden"},{status:403});const b=await req.json(),id=text(b.id,100);
 if(b.entity==="employee"){if(id===user.uid)return NextResponse.json({message:"You cannot remove your own HR account."},{status:400});const account=await adminFirestore.collection("users").doc(id).get();if(!account.exists||account.data()?.role!=="staff")return NextResponse.json({message:"Only regular member accounts can be removed by HR."},{status:400});await adminAuth.deleteUser(id);await adminFirestore.recursiveDelete(adminFirestore.collection("staffProfiles").doc(id));await adminFirestore.collection("users").doc(id).delete();await audit(user.uid,"employee.deleted","staff",id);return NextResponse.json({success:true});}
 const collections:Record<string,string>={policy:"hrPolicies",document:"hrDocuments",announcement:"staffAnnouncements"};const collection=collections[b.entity];if(!collection)return NextResponse.json({message:"Unsupported entity."},{status:400});await adminFirestore.collection(collection).doc(id).delete();await audit(user.uid,`${b.entity}.deleted`,b.entity,b.id);return NextResponse.json({success:true});
}
