"use client";
import { useEffect,useMemo,useState } from "react";
import type { PublicResource,ResourceKind } from "@/types/portal";
import { Search,Download,Eye,Play,FileText,Image as ImageIcon,Mic2,Bell,X,ExternalLink,ChevronLeft,ChevronRight } from "lucide-react";

const filters:["all"|ResourceKind,string][]=[["all","All"],["notice","Notices"],["document","Documents"],["speech","Speeches"],["video","Videos"],["gallery","Gallery"]];
const label:Record<ResourceKind,string>={notice:"Notice",document:"Document",speech:"Speech",video:"Video",gallery:"Gallery"};
function youtubeId(url?:string){return url?.match(/(?:youtu\.be\/|v=|embed\/)([\w-]{11})/)?.[1]||""}
function galleryImages(item:PublicResource){return [...new Set([item.coverImageUrl,...(item.imageUrls||[])].filter((x):x is string=>Boolean(x)))]}

export default function ResourcesClient(){
 const [items,setItems]=useState<PublicResource[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(""),[filter,setFilter]=useState<"all"|ResourceKind>("all"),[search,setSearch]=useState(""),[page,setPage]=useState(0);
 const [viewer,setViewer]=useState<{images:string[];index:number;title:string}|null>(null),[docViewer,setDocViewer]=useState<string|null>(null);
 useEffect(()=>{fetch("/api/resources").then(r=>r.ok?r.json():Promise.reject()).then(d=>setItems(d.resources)).catch(()=>setError("There are currently no resources available. Please check back soon.")).finally(()=>setLoading(false))},[]);
 useEffect(()=>{if(!viewer)return;const key=(e:KeyboardEvent)=>{if(e.key==="Escape")setViewer(null);if(e.key==="ArrowLeft")setViewer(v=>v?{...v,index:(v.index-1+v.images.length)%v.images.length}:v);if(e.key==="ArrowRight")setViewer(v=>v?{...v,index:(v.index+1)%v.images.length}:v)};addEventListener("keydown",key);return()=>removeEventListener("keydown",key)},[viewer]);
 useEffect(()=>{const handle=(e:MouseEvent)=>{const link=(e.target as HTMLElement).closest<HTMLAnchorElement>("a[href]");if(!link||link.hasAttribute("download")||!link.href.includes("firebasestorage.googleapis.com"))return;e.preventDefault();setDocViewer(link.href)};document.addEventListener("click",handle);return()=>document.removeEventListener("click",handle)},[]);
 useEffect(()=>{setPage(0)},[filter,search]);
 const shown=useMemo(()=>items.filter(x=>(filter==="all"||x.kind===filter)&&`${x.title} ${x.description}`.toLowerCase().includes(search.toLowerCase())),[items,filter,search]);
 const paged=shown.slice(page*6,page*6+6); const pageCount=Math.max(1,Math.ceil(shown.length/6));
 const urgent=items.filter(x=>x.kind==="notice"&&x.priority==="urgent");
 return <section id="notices" className="bg-mist min-h-[50vh] py-10 sm:py-16"><div className="max-w-[1200px] mx-auto px-4 sm:px-7">
  {urgent.map(n=><div key={n.id} className="mb-5 rounded-card-sm border border-red-200 bg-red-50 p-4 flex gap-3 text-red-900"><Bell className="w-5 h-5 shrink-0 mt-0.5"/><div><p className="font-extrabold">{n.title}</p><p className="text-sm mt-1">{n.description}</p></div></div>)}
  <div className="bg-paper border border-line rounded-card shadow-card p-4 sm:p-5 flex flex-col lg:flex-row gap-4 lg:items-center lg:justify-between"><div className="flex gap-2 overflow-x-auto pb-1" role="tablist" aria-label="Resource type">{filters.map(([k,v])=><button key={k} onClick={()=>setFilter(k)} className={`shrink-0 min-h-11 rounded-full px-4 font-bold text-sm ${filter===k?"bg-brand text-white":"bg-mist text-ink-soft hover:bg-mist-2"}`}>{v}</button>)}</div><label className="relative block lg:w-80"><span className="sr-only">Search public resources</span><Search className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-ink-soft"/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search resources…" className="w-full rounded-card-sm border border-line bg-white pl-10 pr-4 py-3 outline-none focus:ring-2 focus:ring-brand/30"/></label></div>
  {loading?<div className="py-20 text-center text-ink-soft">Loading public resources…</div>:error?<div className="py-20 text-center text-red-600">{error}</div>:shown.length===0?<div className="bg-white mt-7 rounded-card border border-line p-14 text-center"><FileText className="w-10 h-10 mx-auto text-brand"/><h2 className="text-xl mt-4">There are currently no resources</h2><p className="text-ink-soft mt-2">Please check back soon.</p></div>:<div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-5 mt-7">{paged.map(x=><ResourceCard key={x.id} item={x} openGallery={(images,index)=>setViewer({images,index,title:x.title})}/>)}</div>}{shown.length>6&&<div className="mt-8 flex items-center justify-center gap-4"><button onClick={()=>setPage(p=>Math.max(0,p-1))} disabled={page===0} className="rounded-full border border-line bg-white px-4 py-2 font-bold disabled:opacity-40">Previous</button><span className="text-sm font-bold text-ink-soft">Page {page+1} of {pageCount}</span><button onClick={()=>setPage(p=>Math.min(pageCount-1,p+1))} disabled={page>=pageCount-1} className="rounded-full border border-line bg-white px-4 py-2 font-bold disabled:opacity-40">Next</button></div>}
 </div>{viewer&&<div role="dialog" aria-modal="true" aria-label={`${viewer.title} image viewer`} className="fixed inset-0 z-[100] bg-navy/95 p-4 flex items-center justify-center"><button onClick={()=>setViewer(null)} className="absolute right-4 top-4 text-white p-3 z-10" aria-label="Close image"><X/></button>{viewer.images.length>1&&<button onClick={()=>setViewer({...viewer,index:(viewer.index-1+viewer.images.length)%viewer.images.length})} className="absolute left-3 sm:left-7 text-white bg-black/30 rounded-full p-3" aria-label="Previous image"><ChevronLeft/></button>}<img src={viewer.images[viewer.index]} alt={`${viewer.title} image ${viewer.index+1}`} className="max-w-[calc(100%-5rem)] max-h-[85vh] object-contain"/>{viewer.images.length>1&&<button onClick={()=>setViewer({...viewer,index:(viewer.index+1)%viewer.images.length})} className="absolute right-3 sm:right-7 text-white bg-black/30 rounded-full p-3" aria-label="Next image"><ChevronRight/></button>}<span className="absolute bottom-4 text-white text-sm">{viewer.index+1} / {viewer.images.length}</span></div>}<div>{docViewer&&<div role="dialog" aria-modal="true" aria-label="Document viewer" className="fixed inset-0 z-[110] bg-navy/90 p-3 sm:p-6 flex items-center justify-center"><div className="relative w-full h-full max-w-6xl bg-white rounded-2xl overflow-hidden shadow-card-lg"><button onClick={()=>setDocViewer(null)} className="absolute right-3 top-3 z-10 rounded-full bg-navy text-white px-4 py-2 font-bold" aria-label="Close document viewer">Close</button><iframe src={docViewer} title="Document preview" className="w-full h-full border-0"/></div></div>}</div></section>
}

function ResourceCard({item:x,openGallery}:{item:PublicResource;openGallery:(images:string[],index:number)=>void}){
 const images=galleryImages(x);const id=youtubeId(x.youtubeUrl);
 return <article className="min-w-0 bg-paper border border-line rounded-card shadow-card overflow-hidden flex flex-col">
  {x.kind==="video"&&id?<div className="aspect-video bg-navy"><iframe className="w-full h-full" loading="lazy" src={`https://www.youtube-nocookie.com/embed/${id}`} title={x.title} allowFullScreen/></div>:x.kind==="gallery"&&images.length?<GallerySlideshow images={images} title={x.title} open={openGallery}/>:<div className="h-28 bg-gradient-to-br from-brand to-brand-deep flex items-center justify-center text-white">{x.kind==="notice"?<Bell/>:x.kind==="speech"?<Mic2/>:x.kind==="video"?<Play/>:x.kind==="gallery"?<ImageIcon/>:<FileText/>}</div>}
  <div className="p-5 flex flex-col flex-1"><div className="flex justify-between gap-3 items-start"><span className="text-xs uppercase tracking-wider font-extrabold text-brand-700">{label[x.kind]}</span>{x.priority&&<span className={`text-xs font-bold capitalize ${x.priority==="urgent"?"text-red-600":x.priority==="important"?"text-amber-700":"text-ink-soft"}`}>{x.priority}</span>}</div><h2 className="text-xl mt-3 break-words">{x.title}</h2>{x.speaker&&<p className="text-sm text-brand-700 font-bold mt-2">{x.speaker}</p>}<p className="text-ink-soft mt-3 leading-relaxed line-clamp-4">{x.description}</p><p className="text-xs text-ink-soft mt-4">{x.date||x.publishDate}</p><div className="mt-auto pt-5 flex flex-wrap gap-2">{x.fileUrl&&<><a href={x.fileUrl} target="_blank" rel="noreferrer" className="inline-flex min-h-11 items-center gap-2 rounded-full bg-brand text-white px-4 font-bold"><Eye className="w-4 h-4"/>View</a><a href={x.fileUrl} download={x.fileName||true} target="_blank" rel="noreferrer" className="inline-flex min-h-11 items-center gap-2 rounded-full border border-line bg-white text-brand-700 px-4 font-bold"><Download className="w-4 h-4"/>Download</a></>}{x.youtubeUrl&&!id&&<a href={x.youtubeUrl} target="_blank" rel="noreferrer" className="inline-flex min-h-11 items-center gap-2 rounded-full bg-brand text-white px-4 font-bold"><ExternalLink className="w-4 h-4"/>Watch</a>}</div></div>
 </article>
}

function GallerySlideshow({images,title,open}:{images:string[];title:string;open:(images:string[],index:number)=>void}){
 const [index,setIndex]=useState(0);useEffect(()=>{if(images.length<2)return;const timer=setInterval(()=>setIndex(i=>(i+1)%images.length),4500);return()=>clearInterval(timer)},[images.length]);
 return <div className="relative aspect-[16/10] bg-mist overflow-hidden group"><button onClick={()=>open(images,index)} className="w-full h-full"><img src={images[index]} alt={`${title} image ${index+1}`} loading="lazy" className="w-full h-full object-cover transition-opacity"/></button>{images.length>1&&<><button onClick={()=>setIndex((index-1+images.length)%images.length)} className="absolute left-2 top-1/2 -translate-y-1/2 bg-navy/70 text-white rounded-full p-2 opacity-100 sm:opacity-0 sm:group-hover:opacity-100 transition" aria-label="Previous gallery image"><ChevronLeft className="w-5 h-5"/></button><button onClick={()=>setIndex((index+1)%images.length)} className="absolute right-2 top-1/2 -translate-y-1/2 bg-navy/70 text-white rounded-full p-2 opacity-100 sm:opacity-0 sm:group-hover:opacity-100 transition" aria-label="Next gallery image"><ChevronRight className="w-5 h-5"/></button><span className="absolute bottom-2 right-2 bg-navy/70 text-white rounded-full px-2 py-1 text-xs">{index+1}/{images.length}</span></>}</div>
}










