"use client";
import PortalGuard from "@/components/PortalGuard";
import Link from "next/link";
import { usePathname,useRouter } from "next/navigation";
import { useEffect,useState } from "react";
import { signOut } from "firebase/auth";
import { auth } from "@/lib/firebase";
import { Bell,BookOpenCheck,MessageSquareText,X } from "lucide-react";

export default function StaffShell({children}:{children:React.ReactNode}){
 const path=usePathname(),router=useRouter();
 const [announcements,setAnnouncements]=useState<any[]>([]),[notifications,setNotifications]=useState<any[]>([]),[policies,setPolicies]=useState<any[]>([]),[documents,setDocuments]=useState<any[]>([]),[open,setOpen]=useState(false),[selected,setSelected]=useState<any>(),[policyOpened,setPolicyOpened]=useState(false),[acknowledging,setAcknowledging]=useState(false),[policyError,setPolicyError]=useState("");
 const unread=announcements.filter(x=>!x.read).length+notifications.filter(x=>!x.read).length,requiredPolicy=policies.find(x=>x.active&&x.acknowledgementRequired&&!x.acknowledged),requiredDocument=documents.find(x=>x.active&&x.acknowledgementRequired&&!x.acknowledged),requiredItem=requiredPolicy||requiredDocument;
 async function load(){const r=await fetch("/api/hr",{cache:"no-store"}),d=r.ok?await r.json():null;setAnnouncements(d?.announcements||[]);setNotifications(d?.notifications||[]);setPolicies(d?.policies||[]);setDocuments(d?.documents||[])}
 useEffect(()=>{load().catch(()=>{})},[]);
 useEffect(()=>{if(!open&&!requiredItem)return;const previous=document.body.style.overflow;document.body.style.overflow="hidden";const escape=(event:KeyboardEvent)=>{if(event.key==="Escape"&&!requiredItem)setOpen(false)};document.addEventListener("keydown",escape);return()=>{document.body.style.overflow=previous;document.removeEventListener("keydown",escape)}},[open,requiredItem]);
 async function readAnnouncement(item:any){if(!item.read){setAnnouncements(xs=>xs.map(x=>x.id===item.id?{...x,read:true}:x));await fetch("/api/hr",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"readAnnouncement",announcementId:item.id})})}window.location.assign(`/staff/hr?section=Announcements&record=${encodeURIComponent(item.id)}`)}
 async function readNotification(item:any){setSelected({...item,type:"notification",description:item.message,publishDate:item.createdAt});if(!item.read){setNotifications(xs=>xs.map(x=>x.id===item.id?{...x,read:true}:x));await fetch("/api/hr",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"readNotification",notificationId:item.id})})}}
 async function acknowledge(){if(!requiredItem)return;setAcknowledging(true);setPolicyError("");try{const document=requiredItem===requiredDocument,r=await fetch("/api/hr",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(document?{action:"acknowledgeDocument",documentId:requiredItem.id}:{action:"acknowledge",policyId:requiredItem.id})}),d=await r.json();if(!r.ok)throw new Error(d.message||"Acknowledgement could not be saved.");setPolicyOpened(false);if(document)setDocuments(xs=>xs.map(x=>x.id===requiredItem.id?{...x,acknowledged:true}:x));else setPolicies(xs=>xs.map(x=>x.id===requiredItem.id?{...x,acknowledged:true}:x))}catch(error){setPolicyError(error instanceof Error?error.message:"Acknowledgement could not be saved.")}finally{setAcknowledging(false)}}
 async function logout(){await fetch("/api/auth/session",{method:"DELETE"});await signOut(auth);router.push("/staff/login")}
 return <PortalGuard role="staff"><div className="min-h-screen bg-mist">
  <header className="bg-navy-deep text-white sticky top-0 z-40"><div className="max-w-[1200px] mx-auto min-h-20 px-4 sm:px-7 flex flex-wrap items-center justify-between gap-3 py-3"><Link href="/staff/dashboard"><span className="text-on-blue text-xs uppercase tracking-widest font-bold">UpTech</span><strong className="block text-lg">Member Portal</strong></Link><nav className="flex items-center gap-1"><Link href="/staff/dashboard" className={`px-3 sm:px-4 py-2 rounded-full font-bold text-sm ${path==="/staff/dashboard"?"bg-white text-navy":"text-on-blue"}`}>Dashboard</Link><Link href="/staff/hr" className={`px-3 sm:px-4 py-2 rounded-full font-bold text-sm ${path.startsWith("/staff/hr")?"bg-white text-navy":"text-on-blue"}`}>HR</Link><button onClick={()=>{setSelected(undefined);setOpen(true)}} className="relative p-2.5 rounded-full text-on-blue hover:bg-white/10" aria-label={`${unread} unread updates`}><Bell className="w-5 h-5"/>{unread>0&&<span className="absolute -right-0.5 -top-0.5 min-w-5 h-5 px-1 grid place-items-center rounded-full bg-red-500 text-white text-[11px] font-black">{unread>9?"9+":unread}</span>}</button><button onClick={logout} className="px-2 sm:px-3 py-2 text-sm font-bold text-on-blue">Sign out</button></nav></div></header>
  {children}
  {open&&<NotificationCenter announcements={announcements} notifications={notifications} selected={selected} selectAnnouncement={readAnnouncement} selectNotification={readNotification} back={()=>setSelected(undefined)} close={()=>setOpen(false)}/>} 
  {requiredItem&&<PolicyGate policy={requiredItem} itemType={requiredItem===requiredDocument?"document":"policy"} opened={policyOpened} setOpened={setPolicyOpened} error={policyError} acknowledging={acknowledging} acknowledge={acknowledge}/>} 
 </div></PortalGuard>
}

function NotificationCenter({announcements,notifications,selected,selectAnnouncement,selectNotification,back,close}:any){const target=selected?.entity==="leave"?"My Leave":"My Requests",href=selected?.sourceId?`/staff/hr?section=${encodeURIComponent(target)}&record=${encodeURIComponent(selected.sourceId)}`:`/staff/hr?section=${encodeURIComponent(target)}`;return <div className="fixed inset-0 z-[100] bg-navy/60 p-3 sm:p-6 flex justify-end" onMouseDown={e=>{if(e.currentTarget===e.target)close()}}><aside role="dialog" aria-modal="true" aria-label="Member notifications" className="w-full max-w-md h-full bg-white rounded-card shadow-card-lg overflow-hidden flex flex-col"><header className="p-5 border-b border-line flex items-center justify-between"><div><p className="text-xs uppercase font-extrabold text-brand-700">Notification center</p><h2 className="text-2xl mt-1">Updates</h2></div><button onClick={close} className="p-2 rounded-full hover:bg-mist" aria-label="Close"><X/></button></header>{selected?<article className="p-6 overflow-y-auto"><button onClick={back} className="text-sm font-bold text-brand-700">← All updates</button><p className="mt-6 text-xs font-extrabold uppercase text-brand-700">{selected.type==="notification"?"HR update":"Member announcement"}</p><h3 className="text-2xl mt-2">{selected.title}</h3><p className="text-sm text-ink-soft mt-2">{selected.publishDate?new Date(selected.publishDate).toLocaleString():"Recently published"}</p><p className="mt-6 leading-relaxed whitespace-pre-wrap">{selected.description}</p>{selected.type==="notification"&&<Link href={href} onClick={close} className="btn inline-flex mt-6">Open this {selected.entity==="leave"?"leave request":"HR request"}</Link>}</article>:<div className="overflow-y-auto p-3">{notifications.length>0&&<section><p className="px-3 py-2 text-[11px] font-extrabold uppercase tracking-wider text-ink-soft">HR request updates</p>{notifications.map((item:any)=><UpdateRow key={item.id} item={item} icon={<MessageSquareText/>} open={()=>selectNotification(item)}/>)}</section>}<section><p className="px-3 py-2 text-[11px] font-extrabold uppercase tracking-wider text-ink-soft">Announcements</p>{announcements.length?announcements.map((item:any)=><UpdateRow key={item.id} item={item} icon={<Bell/>} open={()=>selectAnnouncement(item)}/>):<p className="p-6 text-center text-ink-soft">No member announcements yet.</p>}</section>{!notifications.length&&!announcements.length&&<div className="p-10 text-center text-ink-soft"><Bell className="mx-auto mb-3"/><p>You are all caught up.</p></div>}</div>}</aside></div>}
function UpdateRow({item,icon,open}:{item:any;icon:React.ReactNode;open:()=>void}){return <button onClick={open} className={`w-full text-left rounded-2xl p-4 mb-2 border ${item.read?"border-transparent hover:bg-mist":"border-brand/20 bg-brand/5"}`}><div className="flex gap-3"><span className="text-brand w-5 h-5 shrink-0 [&>svg]:w-5 [&>svg]:h-5">{icon}</span><span className="min-w-0 flex-1"><span className="font-extrabold block">{item.title}</span><span className="text-xs text-ink-soft block mt-1">{item.publishDate||item.createdAt?new Date(item.publishDate||item.createdAt).toLocaleDateString():"Recently"}{!item.read?" · Unread":""}</span><span className="text-sm text-ink-soft line-clamp-2 mt-2 block">{item.message||item.description}</span></span>{!item.read&&<span className="w-2 h-2 rounded-full bg-brand mt-1"/>}</div></button>}
function PolicyGate({policy,itemType,opened,setOpened,error,acknowledging,acknowledge}:any){return <div className="fixed inset-0 z-[120] bg-navy/75 p-4 grid place-items-center"><section role="dialog" aria-modal="true" aria-label={`Required ${itemType} acknowledgement`} className={`bg-white rounded-card shadow-card-lg w-full ${opened&&policy.fileUrl?"max-w-5xl":"max-w-xl"} max-h-[calc(100vh-2rem)] overflow-y-auto p-6 sm:p-8`}><span className="w-12 h-12 rounded-2xl bg-amber-100 text-amber-800 grid place-items-center"><BookOpenCheck/></span><p className="mt-5 text-xs uppercase tracking-wider font-extrabold text-amber-700">Required reading · {itemType}</p><h2 className="text-2xl mt-1">{policy.title}</h2>{itemType==="policy"&&<p className="text-sm text-ink-soft mt-2">Effective {policy.effectiveDate||"immediately"} · Version {policy.version||1}</p>}<p className="mt-5 leading-relaxed whitespace-pre-wrap">{policy.description}</p>{policy.fileUrl&&!opened&&<button onClick={()=>setOpened(true)} className="pill mt-6">Read {itemType} on this page</button>}{opened&&policy.fileUrl&&<div className="mt-6 rounded-2xl border border-line overflow-hidden bg-mist"><iframe src={policy.fileUrl} title={`${policy.title} ${itemType}`} className="w-full h-[55vh] border-0 bg-white"/></div>}{!policy.fileUrl&&!opened&&<button onClick={()=>setOpened(true)} className="pill mt-6">I have read the {itemType} above</button>}<div className="mt-6 pt-5 border-t border-line"><p className="text-sm text-ink-soft">Read the {itemType} on this page, then confirm your acknowledgement to continue.</p>{error&&<p role="alert" className="mt-3 rounded-xl bg-red-50 text-red-700 p-3 text-sm font-semibold">{error}</p>}<button disabled={!opened||acknowledging} onClick={acknowledge} className="btn mt-4 disabled:opacity-40">{acknowledging?"Saving acknowledgement…":"Acknowledge and continue"}</button></div></section></div>}
