"use client";
import AdminShell from "@/components/AdminShell";
import {useEffect,useState} from "react";
import {Trash2,Pencil,Eye,EyeOff,Plus} from "lucide-react";
export default function Page(){
 const [items,setItems]=useState<any[]>([]),[open,setOpen]=useState(false),[editing,setEditing]=useState<any>(null),[confirmDelete,setConfirmDelete]=useState<string|null>(null),[deleting,setDeleting]=useState(false);
 async function load(){const r=await fetch("/api/resources?admin=1");if(r.ok)setItems((await r.json()).resources)} useEffect(()=>{load()},[]);
 async function toggle(x:any){await fetch(`/api/resources/${x.id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({published:!x.published})});load()}
 async function remove(){if(!confirmDelete)return;setDeleting(true);try{await fetch(`/api/resources/${confirmDelete}`,{method:"DELETE"});setConfirmDelete(null);load()}finally{setDeleting(false)}}
 return <AdminShell><main className="max-w-[1200px] mx-auto px-5 py-8"><div className="flex justify-between items-end"><div><p className="text-xs font-extrabold uppercase text-brand-700">Public information</p><h1 className="text-3xl mt-1">Resource Management</h1><p className="text-ink-soft mt-2">Create, edit, publish and maintain public content.</p></div><button onClick={()=>{setEditing({kind:"document",title:"",description:"",published:false});setOpen(true)}} className="rounded-full bg-brand text-white px-5 py-3 font-bold"><Plus className="inline w-4 h-4 mr-2"/>Add resource</button></div>{open&&<ResourceForm initial={editing} close={()=>setOpen(false)} saved={()=>{setOpen(false);load()}}/>}<div className="mt-7 grid gap-3">{items.map(x=><article key={x.id} className="bg-white rounded-2xl border border-line p-4 flex items-center justify-between"><div><span className="text-xs uppercase font-bold text-brand-700">{x.kind}</span><h2 className="text-lg font-bold">{x.title}</h2><p className="text-sm text-ink-soft">{x.published?"Published":"Draft"}</p></div><div className="flex gap-2"><button onClick={()=>{setEditing(x);setOpen(true)}} className="p-3 rounded-full bg-brand/10 text-brand"><Pencil/></button><button onClick={()=>toggle(x)} className="p-3 rounded-full bg-mist">{x.published?<EyeOff/>:<Eye/>}</button><button onClick={()=>setConfirmDelete(x.id)} className="p-3 rounded-full bg-red-50 text-red-600"><Trash2/></button></div></article>)}</div>{confirmDelete&&<div className="fixed inset-0 z-50 bg-navy/70 p-4 grid place-items-center"><div role="dialog" className="w-full max-w-md rounded-3xl bg-white p-7"><h2 className="text-center text-2xl">Delete resource?</h2><p className="text-center text-ink-soft mt-2">This permanently removes the resource.</p><div className="grid grid-cols-2 gap-3 mt-7"><button onClick={()=>setConfirmDelete(null)} className="rounded-full border border-line py-3 font-bold">Cancel</button><button onClick={remove} disabled={deleting} className="rounded-full bg-red-600 text-white py-3 font-bold">{deleting?"Deleting…":"Delete resource"}</button></div></div></div>}</main></AdminShell>
}
function ResourceForm({initial,close,saved}:{initial:any;close:()=>void;saved:()=>void}){const [f,setF]=useState(initial);async function submit(e:any){e.preventDefault();const url=f.id?`/api/resources/${f.id}`:"/api/resources";await fetch(url,{method:f.id?"PATCH":"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(f)});saved()}return <form onSubmit={submit} className="mt-6 bg-white rounded-2xl border border-line p-6 grid gap-4"><input value={f.title||""} required placeholder="Title" onChange={e=>setF({...f,title:e.target.value})} className="input"/><textarea value={f.description||""} required placeholder="Description" onChange={e=>setF({...f,description:e.target.value})} className="input"/><select value={f.kind} onChange={e=>setF({...f,kind:e.target.value})} className="input"><option>document</option><option>speech</option><option>notice</option><option>video</option><option>gallery</option></select><div><button className="rounded-full bg-brand text-white px-5 py-3 font-bold">Save</button><button type="button" onClick={close} className="ml-3 rounded-full border px-5 py-3 font-bold">Cancel</button></div></form>}
