"use client";

import AdminShell from "@/components/AdminShell";
import { CalendarDays,ChevronDown,ChevronUp,UsersRound } from "lucide-react";
import { useEffect,useMemo,useState } from "react";

type Attendance={employeeId:string;name:string;email:string;status:""|"Present"|"Absent";reason:string};
type Meeting={id:string;title:string;meetingDate:string;attendance:Attendance[];updatedAt?:string};

export default function Page(){
  const [meetings,setMeetings]=useState<Meeting[]>([]),[loading,setLoading]=useState(true),[creating,setCreating]=useState(false),[title,setTitle]=useState("Board meeting"),[meetingDate,setMeetingDate]=useState(""),[open,setOpen]=useState(""),[query,setQuery]=useState(""),[page,setPage]=useState(1),[message,setMessage]=useState("");
  async function load(){const response=await fetch("/api/board-meetings",{cache:"no-store"}),data=await response.json();if(response.ok)setMeetings(data.meetings||[]);else setMessage(data.message||"Meetings could not be loaded.");setLoading(false)}
  useEffect(()=>{load()},[]);
  const filtered=useMemo(()=>meetings.filter(item=>`${item.title} ${item.meetingDate}`.toLowerCase().includes(query.toLowerCase())),[meetings,query]),size=6,pages=Math.max(1,Math.ceil(filtered.length/size)),shown=filtered.slice((Math.min(page,pages)-1)*size,Math.min(page,pages)*size);
  useEffect(()=>setPage(1),[query]);
  async function create(){setMessage("");setCreating(true);const response=await fetch("/api/board-meetings",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({title,meetingDate})}),data=await response.json();setCreating(false);if(!response.ok)return setMessage(data.message||"Meeting could not be created.");setMeetingDate("");setMessage("Meeting created. Record attendance below.");await load();setOpen(data.id)}
  function updateMeeting(id:string,attendance:Attendance[]){setMeetings(items=>items.map(item=>item.id===id?{...item,attendance}:item))}
  return <AdminShell><main className="max-w-[1200px] mx-auto px-4 sm:px-7 py-8 sm:py-10"><p className="text-brand-700 font-extrabold uppercase tracking-[.14em] text-xs">Governance</p><h1 className="text-3xl sm:text-4xl mt-1">Board Meetings</h1><p className="text-ink-soft mt-2">Schedule meetings and keep a clear attendance record.</p>{message&&<p role="status" className="mt-5 rounded-2xl border border-line bg-white p-4 font-semibold">{message}</p>}<section className="mt-7 bg-white border border-line rounded-card shadow-card p-5 sm:p-7"><h2 className="text-xl">Add meeting</h2><div className="grid md:grid-cols-[1fr_240px_auto] gap-3 mt-4 items-end"><label className="text-sm font-bold">Meeting title<input className="input" value={title} maxLength={120} onChange={event=>setTitle(event.target.value)}/></label><label className="text-sm font-bold">Meeting date<input className="input" type="date" required value={meetingDate} onChange={event=>setMeetingDate(event.target.value)}/></label><button disabled={creating||!meetingDate} onClick={create} className="btn mb-0.5 disabled:opacity-50">{creating?"Creating…":"Create meeting"}</button></div></section><div className="mt-6 flex flex-wrap items-end justify-between gap-3"><label className="text-sm font-bold w-full sm:w-96">Search meetings<input className="input" placeholder="Title or date" value={query} onChange={event=>setQuery(event.target.value)}/></label><p className="text-sm text-ink-soft">{filtered.length} meeting{filtered.length===1?"":"s"}</p></div><div className="grid gap-4 mt-4">{loading?<div className="bg-white rounded-card border border-line p-8 text-ink-soft">Loading meetings…</div>:shown.length?shown.map(meeting=><MeetingCard key={meeting.id} meeting={meeting} expanded={open===meeting.id} toggle={()=>setOpen(open===meeting.id?"":meeting.id)} update={attendance=>updateMeeting(meeting.id,attendance)} notify={setMessage}/>):<div className="bg-white rounded-card border border-dashed border-line p-12 text-center"><CalendarDays className="mx-auto text-brand"/><h2 className="text-xl mt-4">No board meetings yet</h2><p className="text-ink-soft mt-2">Create the first meeting above.</p></div>}</div>{pages>1&&<div className="mt-5 flex items-center justify-between bg-white border border-line rounded-2xl p-3"><button disabled={page===1} onClick={()=>setPage(page-1)} className="pill disabled:opacity-40">Previous</button><strong className="text-sm">Page {page} of {pages}</strong><button disabled={page===pages} onClick={()=>setPage(page+1)} className="pill disabled:opacity-40">Next</button></div>}</main></AdminShell>;
}

function MeetingCard({meeting,expanded,toggle,update,notify}:{meeting:Meeting;expanded:boolean;toggle:()=>void;update:(rows:Attendance[])=>void;notify:(message:string)=>void}){
  const [saving,setSaving]=useState(false);const present=meeting.attendance.filter(row=>row.status==="Present").length,absent=meeting.attendance.filter(row=>row.status==="Absent").length,unrecorded=meeting.attendance.length-present-absent;
  function change(index:number,patch:Partial<Attendance>){update(meeting.attendance.map((row,rowIndex)=>rowIndex===index?{...row,...patch,...(patch.status==="Present"?{reason:""}:{})}:row))}
  async function save(){setSaving(true);notify("");const response=await fetch("/api/board-meetings",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({id:meeting.id,attendance:meeting.attendance})}),data=await response.json();setSaving(false);notify(response.ok?"Attendance saved successfully.":data.message||"Attendance could not be saved.")}
  return <article className="bg-white border border-line rounded-card shadow-card overflow-hidden"><button onClick={toggle} className="w-full p-5 sm:p-6 text-left flex items-center justify-between gap-4"><span className="flex items-center gap-4"><span className="w-11 h-11 rounded-2xl bg-brand/10 text-brand grid place-items-center"><CalendarDays/></span><span><strong className="block text-xl">{meeting.title}</strong><span className="text-ink-soft text-sm">{new Date(`${meeting.meetingDate}T12:00:00`).toLocaleDateString(undefined,{year:"numeric",month:"long",day:"numeric"})}</span></span></span><span className="flex items-center gap-3"><span className="hidden sm:block text-sm text-ink-soft">{present} present · {absent} absent{unrecorded?` · ${unrecorded} not recorded`:""}</span>{expanded?<ChevronUp/>:<ChevronDown/>}</span></button>{expanded&&<div className="border-t border-line p-5 sm:p-6"><div className="flex items-center gap-2 mb-4"><UsersRound className="text-brand"/><h3>Attendance</h3></div><div className="grid gap-3">{meeting.attendance.map((row,index)=><div key={row.employeeId} className="grid md:grid-cols-[minmax(180px,1fr)_190px_minmax(220px,1fr)] gap-3 items-end rounded-2xl bg-mist p-4"><div className="min-w-0"><strong className="block">{row.name}</strong><span className="text-xs text-ink-soft break-all">{row.email}</span></div><label className="text-sm font-bold">Attendance<select className="input bg-white" value={row.status} onChange={event=>change(index,{status:event.target.value as Attendance["status"]})}><option value="">Not recorded</option><option>Present</option><option>Absent</option></select></label><label className="text-sm font-bold">Reason if absent<input className="input bg-white disabled:opacity-50" disabled={row.status!=="Absent"} required={row.status==="Absent"} placeholder="Enter absence reason" value={row.reason} onChange={event=>change(index,{reason:event.target.value})}/></label></div>)}</div><button disabled={saving||!meeting.attendance.length} onClick={save} className="btn mt-5 disabled:opacity-50">{saving?"Saving…":"Save attendance"}</button></div>}</article>;
}
